/**
 * Nocp Startpage
 * Copyright (c) NriotHrreion 2020
 * 
 * Thank you for your use.
 * If the startpage has bug, please tell me on github, I'll fix it!
 * 
 * License: Apache-2.0
 */
document.title=chrome.i18n.getMessage("tab");document.getElementById("s").placeholder=chrome.i18n.getMessage("searchbox");document.getElementById("account").title=chrome.i18n.getMessage("title_2");document.getElementById("more").title=chrome.i18n.getMessage("title_3");document.getElementById("m-tit").innerHTML=chrome.i18n.getMessage("more");document.getElementById("sbox").title=chrome.i18n.getMessage("title_1");document.onkeydown=function(f){var d=window.event||f;var c=d.keyCode||d.which||d.charCode;if(c==13){var a=document.getElementById("s").value;var b=/^([hH][tT]{2}[pP]:\/\/|[hH][tT]{2}[pP][sS]:\/\/|[fF][tT][pP]:\/\/)+(([A-Za-z0-9-~]+)\.)+([A-Za-z0-9-~\/])+$/;if(!b.test(a)){window.location.href="https://baidu.com/s?wd="+a}else{window.location.href=a}}};chrome.storage.local.get({bgimg:true},function(a){if(a.bgimg==true){document.querySelector("body").style.backgroundImage="url(https://api.misakal.xyz/Bing-Image)"}else{if(a.bgimg==false){document.querySelector("body").style.backgroundImage="url(image/bg.jpg)"}}});var morestat=0;var more=document.getElementById("more-item");document.getElementById("more").onclick=function(){consoleInfo("Event",this,"event","no error");if(morestat==0){more.style.display="block";morestat=1}else{if(morestat==1){more.style.display="none";morestat=0}}};document.getElementById("account").onclick=function(){consoleInfo("Event",this,"event","no error");};document.addEventListener("visibilitychange",function(){var a=document.hidden;if(a){chrome.browserAction.setBadgeText({text:"off"});chrome.browserAction.setBadgeBackgroundColor({color:[192,0,0,111]});chrome.contextMenus.update("newpage",{visible:true})}else{chrome.browserAction.setBadgeText({text:"on"});chrome.browserAction.setBadgeBackgroundColor({color:[74,111,100,34]});chrome.contextMenus.update("newpage",{visible:false})}});window.onbeforeunload=function(){chrome.browserAction.setBadgeText({text:"off"});chrome.browserAction.setBadgeBackgroundColor({color:[192,0,0,111]});chrome.contextMenus.update("newpage",{visible:true})};chrome.browserAction.setBadgeText({text:"on"});chrome.browserAction.setBadgeBackgroundColor({color:[74,111,100,34]});chrome.contextMenus.update("newpage",{visible:false});function setOpacity(a,b){if(a.filters){a.style.filter="alpha(opacity="+b+")"}else{a.style.opacity=b/100}}